service: fspo-landing
runtime: python37
#default_expiration: "365d"

handlers:
- url: /img
  static_dir: img

- url: /static
  static_dir: static

- url: /.*
  secure: always
  static_files: landing.html
  upload: landing.html